project:
  type: website
  render: 
    - "*.qmd"

website:
  title: "Linear Algebra for Biologists"
  navbar:
    left:
      - href: index.qmd
        text: About this course
      - href: setup.qmd
        text: Setup
      - text: Modules
        menu: 
          - href: modules/workshop_materials.qmd
            text: "Workshop slides"
          - href: modules/homework.qmd
            text: "Practice and exploration"
      - href: instructor_info.qmd
        text: Contact
        
resources:
  - scripts/linear_algebra_participant.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

